repo: "ethereumoptimism"

cert-manager:
  installCRDs: true

# represents the email for cloudflare config
# this should be a secret
CLOUDFLARE_EMAIL: "mark@optimism.io"
cloudflare_dns_rpc_replicas: "1"

# letsencypt is the information required for automatic TLS certificate
# generation through Lets Encrypt
letsencrypt:
  email: "mark@optimism.io"
  acmeServer:
    staging: "https://acme-staging-v02.api.letsencrypt.org/directory"
    prod: "https://acme-v02.api.letsencrypt.org/directory"

internal_eth_http_url: "http://failover-proxy:8000"

sequencer:
  env:
  - name: DATADIR
    value: '/geth'
  - name: RPC_ENABLE
    value: 'true'
  - name: RPC_ADDR
    value: '0.0.0.0'
  - name: RPC_CORS_DOMAIN
    value: '*'
  - name: RPC_VHOSTS
    value: '*'
  - name: RPC_PORT
    value: '8545'
  - name: WS
    value: 'true'
  - name: WS_ADDR
    value: '0.0.0.0'
  - name: TARGET_GAS_LIMIT
    value: '11000000'
  - name: RPC_API
    value: 'eth,rollup,net,web3'
  - name: WS_API
    value: 'eth,rollup,net,web3'
  - name: WS_ORIGINS
    value: '*'
  - name: GASPRICE
    value: '0'
  - name: NO_USB
    value: 'true'
  - name: GCMODE
    value: 'archive'
  - name: NO_DISCOVER
    value: 'true'
  - name: ETH1_SYNC_SERVICE_ENABLE
    value: 'true'
  - name: USING_OVM
    value: 'true'
  - name: ROLLUP_MAX_CALLDATA_SIZE
    value: '40000'

batch_submitter:
  env:
  - name: POLL_INTERVAL
    value: '15000'
  - name: L2_NODE_WEB3_URL
    value: 'http://sequencer:8545'
  - name: DEBUG
    value: 'info*,error*,warn*,debug*'
  - name: CLEAR_PENDING_TXS
    value: 'false'
  - name: RETRIES
    value: '60'

data_transport_layer:
  env:
  - name: DATA_TRANSPORT_LAYER__SYNC_FROM_L1
    value: 'true'
  - name: DATA_TRANSPORT_LAYER__SYNC_FROM_L2
    value: 'false'
  - name: DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT
    value: 'http://sequencer:8545'
  - name: DATA_TRANSPORT_LAYER__DB_PATH
    value: '/db'
  - name: DATA_TRANSPORT_LAYER__SERVER_PORT
    value: '7878'
  - name: DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL
    value: '1000'
  - name: DATA_TRANSPORT_LAYER__POLLING_INTERVAL
    value: '500'
  - name: DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL
    value: '2000'
  - name: DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS
    value: 'true'
  - name: DATA_TRANSPORT_LAYER__SERVER_HOSTNAME
    value: '0.0.0.0'

message_relayer:
  env:
  - name: L2_NODE_WEB3_URL
    value: 'http://sequencer:8545'

gas_oracle:
  GAS_PRICE_ORACLE_SIGNIFICANT_FACTOR: '0.05'
  GAS_PRICE_ORACLE_METRICS_ENABLE: 'true'
  GAS_PRICE_ORACLE_METRICS_HTTP: '0.0.0.0'
  GAS_PRICE_ORACLE_METRICS_PORT: '6060'
  GAS_PRICE_ORACLE_LAYER_TWO_HTTP_URL: 'http://sequencer:8545'

deploy_secrets: false
