apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-submitter
  labels:
    app: batch-submitter
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: batch-submitter

  template:
    metadata:
      labels:
        app: batch-submitter
    spec:
      restartPolicy: Always
      initContainers:
      - name: wait-for-l2
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l2.sh']
        env:
        - name: L2_NODE_WEB3_URL
          value: 'http://sequencer:8545'
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait

      - name: wait-for-l1
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l1.sh']
        env:
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait

      containers:
      - name: batch-submitter
        image: "{{ .Values.repo }}/batch-submitter:{{ .Values.batch_submitter.tag }}"
        imagePullPolicy: Always

        ports:
        - containerPort: 7300
          name: metrics

        volumeMounts:
        - name: liveliness-script
          mountPath: /script/liveliness

        livenessProbe:
          exec:
            command:
              - /script/liveliness/test.sh
              - run-batch-submitter.js
          initialDelaySeconds: 15
          periodSeconds: 10

        resources:
{{ toYaml .Values.batch_submitter.resources | indent 10 }}

        env:
{{ toYaml .Values.batch_submitter.env | indent 8 }}
        - name: RUN_STATE_BATCH_SUBMITTER
          value: {{ .Values.batch_submitter.runStateBatchSubmitter | quote }}
        - name: RUN_TX_BATCH_SUBMITTER
          value: {{ .Values.batch_submitter.runTxBatchSubmitter | quote }}
        - name: L1_NODE_WEB3_URL
          valueFrom:
            secretKeyRef:
              name: ethereum-http-url
              key: ETH_HTTP_URL
        - name: DEPLOYER_HTTP
          value: {{ .Values.batch_submitter.DEPLOYER_HTTP | quote }}
        - name: NUM_CONFIRMATIONS
          value: {{ .Values.batch_submitter.numConfirmations | quote }}
        - name: SAFE_MINIMUM_ETHER_BALANCE
          value: {{ .Values.batch_submitter.safeMinimumEtherBalance | quote }}
        - name: ADDRESS_MANAGER_ADDRESS
          value: {{ .Values.batch_submitter.addressManagerAddress | quote }}
        - name: MAX_GAS_PRICE_IN_GWEI
          value: {{ .Values.batch_submitter.maxGasPriceInGwei | quote }}
        - name: MIN_L1_TX_SIZE
          value: {{ .Values.batch_submitter.minL1TxSize | quote }}
        - name: MAX_L1_TX_SIZE
          value: {{ .Values.batch_submitter.maxL1TxSize | quote }}
        - name: MAX_TX_BATCH_COUNT
          value: {{ .Values.batch_submitter.maxTxBatchCount | quote }}
        - name: MAX_STATE_BATCH_COUNT
          value: {{ .Values.batch_submitter.maxStateBatchCount | quote }}
        - name: FINALITY_CONFIRMATIONS
          value: {{ .Values.batch_submitter.finalityConfirmations | quote }}
        - name: GAS_THRESHOLD_IN_GWEI
          value: {{ .Values.batch_submitter.gasThresholdInGwei | quote }}
        - name: RESUBMISSION_TIMEOUT
          value: {{ .Values.batch_submitter.resubmissionTimeout | quote }}
        - name: GAS_RETRY_INCREMENT
          value: {{ .Values.batch_submitter.gasRetryIncrement | quote }}
        - name: MAX_BATCH_SUBMISSION_TIME
          value: {{ .Values.batch_submitter.maxBatchSubmissionTime | quote }}
        - name: BLOCK_OFFSET
          value: {{ .Values.batch_submitter.blockOffset | quote }}
        - name: ETH_NETWORK_NAME
          value: {{ .Values.batch_submitter.ethNetworkName | quote }}
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: batch-submitter-sentry
              key: SENTRY_DSN
        - name: SENTRY_TRACE_RATE
          value: {{ .Values.batch_submitter.sentryTraceRate | quote }}
        - name: USE_SENTRY
          value: {{ .Values.batch_submitter.useSentry | quote }}
        - name: MNEMONIC
          valueFrom:
            secretKeyRef:
              name: batch-submitter-mnemonic
              key: MNEMONIC
        - name: PROPOSER_HD_PATH
          value: {{ .Values.batch_submitter.proposerHdPath | quote }}
{{- if eq (default false $.Values.monitoring_enabled) true }}
        - name: BATCH_SUBMITTER_RUN_METRICS_SERVER
          value: "true"
        - name: BATCH_SUBMITTER_METRICS_PORT
          value: {{ default "7300" .Values.batch_submitter.metrics_port | quote }}
        - name: BATCH_SUBMITTER_METRICS_HOSTNAME
          value: "0.0.0.0"
{{- end }}
        - name: AUTO_FIX_BATCH_OPTIONS_CONF
          value: {{ .Values.batch_submitter.autoFixBatchOptionsConf | quote }}
        - name: NODE_ENV
          value: {{ .Values.batch_submitter.nodeEnv | quote }}

      volumes:
      - name: liveliness-script
        configMap:
          name: liveliness-script
          defaultMode: 0777
      - name: wait-scripts
        configMap:
          name: wait-scripts
          defaultMode: 0777
