apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-transport-layer
  labels:
    app: data-transport-layer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-transport-layer
  serviceName: data-transport-layer
  template:
    metadata:
      labels:
        app: data-transport-layer
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      initContainers:
      - name: wait-for-l1
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l1.sh']
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait
        env:
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}

{{- if eq .Values.backend "local" }}
      - name: wait-for-deployer
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-deployer.sh']
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait
        env:
        - name: URL
          value: {{ .Values.data_transport_layer.DEPLOYER_HTTP | quote }}
{{- end }}

      containers:
      - name: data-transport-layer
        image: "{{ .Values.repo }}/data-transport-layer:{{ .Values.data_transport_layer.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
          protocol: TCP

        volumeMounts:
        - name: liveliness-script
          mountPath: /script/liveliness
        - name: data-transport-layer
          mountPath: /db

        livenessProbe:
          exec:
            command:
              - /script/liveliness/test.sh
              - data-transport-layer.js
          initialDelaySeconds: 15
          periodSeconds: 10

        resources:
{{ toYaml .Values.data_transport_layer.resources | indent 10 }}

        env:
{{ toYaml .Values.data_transport_layer.env | indent 8 }}
        - name: DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT
          value: {{ .Values.internal_eth_http_url | quote }}
        - name: DATA_TRANSPORT_LAYER__L2_CHAIN_ID
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__L2_CHAIN_ID | quote }}
        - name: DATA_TRANSPORT_LAYER__CONFIRMATIONS
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__CONFIRMATIONS | quote }}
        - name: DATA_TRANSPORT_LAYER__ADDRESS_MANAGER
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__ADDRESS_MANAGER | quote }}
        - name: DATA_TRANSPORT_LAYER__SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: data-transport-layer-sentry
              key: SENTRY_DSN
        - name: DATA_TRANSPORT_LAYER__USE_SENTRY
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__USE_SENTRY | quote }}
        - name: DATA_TRANSPORT_LAYER__ENABLE_METRICS
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__ENABLE_METRICS | quote }}
        - name: DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__SENTRY_TRACE_RATE | quote }}
        - name: DATA_TRANSPORT_LAYER__NODE_ENV
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__NODE_ENV | quote }}
        - name: DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME
          value: {{ .Values.data_transport_layer.DATA_TRANSPORT_LAYER__ETH_NETWORK_NAME | quote }}
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}
        - name: DEPLOYER_HTTP
          value: {{ .Values.data_transport_layer.DEPLOYER_HTTP | quote }}

      volumes:
      - name: liveliness-script
        configMap:
          name: liveliness-script
          defaultMode: 0777
      - name: wait-scripts
        configMap:
          name: wait-scripts
          defaultMode: 0777
      - name: data-transport-layer
{{- if eq .Values.backend "gcp" }}
        gcePersistentDisk:
          pdName: {{ required ".Values.gcePersistentDisk.data_transport_layer" .Values.gcePersistentDisk.data_transport_layer }}
          fsType: ext4
{{- else if eq .Values.backend "local" }}
        emptyDir: {}
{{- end }}
