{{- if eq .Values.use_deployer true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer
  labels:
    app: deployer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: deployer

  template:
    metadata:
      labels:
        app: deployer
    spec:
      restartPolicy: Always
      initContainers:
      - name: wait-for-l1
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l1.sh']
        env:
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait

      containers:
      - name: deployer
        image: "{{ .Values.repo }}/deployer:{{ .Values.deployer.tag }}"
        imagePullPolicy: Always
        command: ['/opt/optimism/packages/contracts/deployer.sh']

        resources:
{{ toYaml .Values.deployer.resources | indent 10 }}

        env:
{{ toYaml .Values.deployer.env | indent 10 }}

      volumes:
      - name: wait-scripts
        configMap:
          name: wait-scripts
          defaultMode: 0777
{{ end }}
