apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-proxy
  labels:
    app: failover-proxy
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: failover-proxy

  template:
    metadata:
      labels:
        app: failover-proxy
    spec:
      restartPolicy: Always

      containers:
      - name: failover-proxy
        resources:
{{ toYaml .Values.failover_proxy.resources | indent 10 }}
        image: "{{ .Values.failover_proxy.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: SERVICES
          valueFrom:
            secretKeyRef:
              name: ethereum-http-url
              key: ETH_HTTP_URL

        resources:
{{ toYaml .Values.batch_submitter.resources | indent 10 }}

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
