apiVersion: apps/v1
kind: Deployment
metadata:
  name: gas-oracle
  labels:
    app: gas-oracle
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gas-oracle
  template:
    metadata:
      labels:
        app: gas-oracle
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-l2
          image: nicolaka/netshoot
          command: ['bash', '-c', '/script/wait/wait-for-l2.sh']
          env:
          - name: L2_NODE_WEB3_URL
            value: 'http://sequencer:8545'
          volumeMounts:
          - name: wait-scripts
            mountPath: /script/wait

      containers:
        - name: gas-oracle
          image: "{{ .Values.repo }}/gas-oracle:{{ .Values.gas_oracle.tag }}"
          imagePullPolicy: Always
          env:
            - name: GAS_PRICE_ORACLE_ETHEREUM_HTTP_URL
              valueFrom:
                secretKeyRef:
                  name: optimism-public-geth-nodes
                  key: ETH1_RPC1
            - name: GAS_PRICE_ORACLE_LAYER_TWO_HTTP_URL
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_LAYER_TWO_HTTP_URL | quote }}
            - name: GAS_PRICE_ORACLE_L1_CHAIN_ID
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_L1_CHAIN_ID | quote }}
            - name: GAS_PRICE_ORACLE_L2_CHAIN_ID
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_L2_CHAIN_ID | quote }}
            - name: GAS_PRICE_ORACLE_ENABLE_L1_BASE_FEE
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_ENABLE_L1_BASE_FEE | quote}}
            - name: GAS_PRICE_ORACLE_ENABLE_L2_GAS_PRICE
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_ENABLE_L2_GAS_PRICE | quote}}
            - name: GAS_PRICE_ORACLE_L1_BASE_FEE_SIGNIFICANT_FACTOR
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_L1_BASE_FEE_SIGNIFICANT_FACTOR | quote}}
            - name: GAS_PRICE_ORACLE_TARGET_GAS_PER_SECOND
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_TARGET_GAS_PER_SECOND | quote }}
            - name: GAS_PRICE_ORACLE_MAX_PERCENT_CHANGE_PER_EPOCH
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_MAX_PERCENT_CHANGE_PER_EPOCH | quote }}
            - name: GAS_PRICE_ORACLE_AVERAGE_BLOCK_GAS_LIMIT_PER_EPOCH
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_AVERAGE_BLOCK_GAS_LIMIT_PER_EPOCH | quote }}
            - name: GAS_PRICE_ORACLE_FLOOR_PRICE
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_FLOOR_PRICE | quote }}
            - name: GAS_PRICE_ORACLE_EPOCH_LENGTH_SECONDS
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_EPOCH_LENGTH_SECONDS | quote }}
            - name: GAS_PRICE_ORACLE_LOG_LEVEL
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_LOG_LEVEL | quote }}
            - name: GAS_PRICE_ORACLE_SIGNIFICANT_FACTOR
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_SIGNIFICANT_FACTOR | quote }}
            - name: GAS_PRICE_ORACLE_TRANSACTION_GAS_PRICE
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_TRANSACTION_GAS_PRICE | quote }}
            - name: GAS_PRICE_ORACLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: gas-oracle
                  key: private-key
            - name: GAS_PRICE_ORACLE_METRICS_ENABLE
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_METRICS_ENABLE | quote }}
            - name: GAS_PRICE_ORACLE_METRICS_HTTP
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_METRICS_HTTP | quote }}
            - name: GAS_PRICE_ORACLE_METRICS_PORT
              value: {{ .Values.gas_oracle.GAS_PRICE_ORACLE_METRICS_PORT | quote }}
          ports:
            - name: metrics
              containerPort: {{ int .Values.gas_oracle.GAS_PRICE_ORACLE_METRICS_PORT }}
          resources:
{{ toYaml .Values.gas_oracle.resources | indent 12 }}
      volumes:
        - name: wait-scripts
          configMap:
            name: wait-scripts
            defaultMode: 0777