{{- if eq .Values.use_hardhat true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardhat
  labels:
    app: hardhat
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  selector:
    matchLabels:
      app: hardhat

  replicas: 1

  template:
    metadata:
      labels:
        app: hardhat
    spec:
      restartPolicy: Always

      containers:
      - name: hardhat
        image: "{{ .Values.repo }}/hardhat:{{ .Values.hardhat.tag }}"
        imagePullPolicy: Always

        volumeMounts:
        - name: liveliness-script
          mountPath: /script/liveliness

        livenessProbe:
          exec:
            command:
              - /script/liveliness/test.sh
              - hardhat
          initialDelaySeconds: 15
          periodSeconds: 10

        ports:
        - containerPort: 9545

        resources:
{{ toYaml .Values.hardhat.resources | indent 10 }}

        env:
{{ toYaml .Values.hardhat.env | indent 8 }}

      volumes:
      - name: liveliness-script
        configMap:
          name: liveliness-script
          defaultMode: 0777
{{ end }}
