apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sequencer

  labels:
    app: sequencer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- if eq .Values.letsencrypt.dev true }}
    cert-manager.io/issuer: "letsencrypt-staging"
    {{- else }}
    cert-manager.io/issuer: "letsencrypt-prod"
    {{- end }}
    {{- if eq .Values.use_tls true }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
    {{- if eq .Values.use_cloudflare_dns true }}
    external-dns.alpha.kubernetes.io/hostname: {{ required ".Values.domains.rpc" .Values.domains.rpc }}, {{ required ".Values.domains.websocket" .Values.domains.websocket }}
    external-dns.alpha.kubernetes.io/ttl: "120"
    {{- end }}

spec:
  backend:
    serviceName: sequencer
    servicePort: 8545
  rules:
  - host: {{ .Values.domains.rpc | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: sequencer
          servicePort: 8545
  - host: {{ .Values.domains.websocket | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: sequencer
          servicePort: 8546
  {{- if eq .Values.use_tls true }}
  tls:
  - hosts:
    - {{ .Values.domains.rpc | quote }}
    secretName: {{ .Values.domains.rpc | replace "." "-" }}-tls
  - hosts:
    - {{ .Values.domains.websocket | quote }}
    secretName: {{ .Values.domains.websocket | replace "." "-" }}-tls
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  proxy-connect-timeout: "10"
  proxy-read-timeout: "120"
  proxy-send-timeout: "120"
  use-forwarded-headers: "true"
  ssl-redirect: "true"
  redirect-to-https: "true"
