{{- if eq .Values.use_tls true }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: {{ required ".Values.letsencrypt.acmeServer.staging" .Values.letsencrypt.acmeServer.staging }}
    email: {{ required ".Values.letsencrypt.email" .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: {{ required ".Values.letsencrypt.acmeServer.prod" .Values.letsencrypt.acmeServer.prod }}
    email: {{ required ".Values.letsencrypt.email" .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}
