apiVersion: v1
kind: ConfigMap
metadata:
  name: liveliness-script
  labels:
    app: sequencer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  test.sh: |
    #!/bin/sh
    if [ -z "$1" ]; then
        exit 1
    fi

    if [[ $(ps -ef | grep -v grep | grep "$1" | wc -l) -eq 0 ]]; then
        exit 1
    else
        exit 0
    fi
