{{ if eq .Values.use_message_relayer true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-relayer
  labels:
    app: message-relayer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: message-relayer

  template:
    metadata:
      labels:
        app: message-relayer
    spec:
      restartPolicy: Always
      initContainers:
      - name: wait-for-l2
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l2.sh']
        env:
        - name: L2_NODE_WEB3_URL
          value: 'http://sequencer:8545'
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait
      - name: wait-for-l1
        image: nicolaka/netshoot
        command: ['bash', '-c', '/script/wait/wait-for-l1.sh']
        env:
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}
        volumeMounts:
        - name: wait-scripts
          mountPath: /script/wait

      containers:
      - name: message-relayer
        image: "{{ .Values.repo }}/message-relayer:{{ .Values.message_relayer.tag }}"
        imagePullPolicy: Always

        volumeMounts:
        - name: liveliness-script
          mountPath: /script/liveliness

        livenessProbe:
          exec:
            command:
              - /script/liveliness/test.sh
              - message-relayer
          initialDelaySeconds: 15
          periodSeconds: 10

        resources:
{{ toYaml .Values.message_relayer.resources | indent 10 }}

        env:
{{ toYaml .Values.message_relayer.env | indent 8 }}
        - name: L1_NODE_WEB3_URL
          value: {{ .Values.internal_eth_http_url | quote }}
        - name: DEPLOYER_HTTP
          value: {{ .Values.message_relayer.DEPLOYER_HTTP | quote }}
        - name: ADDRESS_MANAGER_ADDRESS
          value: {{ .Values.message_relayer.ADDRESS_MANAGER_ADDRESS | quote }}
        - name: L1_BLOCK_OFFSET
          value: {{ .Values.message_relayer.L1_BLOCK_OFFSET | quote }}
        - name: HD_PATH
          value: {{ .Values.message_relayer.HD_PATH | quote }}
        - name: MNEMONIC
          valueFrom:
            secretKeyRef:
              name: message-relayer-key
              key: MNEMONIC

      volumes:
      - name: liveliness-script
        configMap:
          name: liveliness-script
          defaultMode: 0777
      - name: wait-scripts
        configMap:
          name: wait-scripts
          defaultMode: 0777
{{- end }}
