{{- if eq $.Values.deploy_secrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: batch-submitter-mnemonic
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  MNEMONIC: {{ b64enc .Values.batch_submitter.mnemonic | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: batch-submitter-sentry
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  SENTRY_DSN: {{ b64enc .Values.batch_submitter.sentryDsn | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-transport-layer-sentry
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  SENTRY_DSN: {{ b64enc .Values.data_transport_layer.sentryDsn | quote }}
---
{{- if eq .Values.use_cloudflare_dns true }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  CF_API_TOKEN: {{ b64enc .Values.cloudflare.api_token | quote }}
  CF_API_KEY: {{ b64enc .Values.cloudflare.api_key | quote }}
  CF_API_EMAIL: {{ b64enc .Values.cloudflare.api_email | quote }}
  ZONE_ID_FILTER: {{ b64enc .Values.cloudflare.zone_id_filter | quote }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ethereum-http-url
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  ETH_HTTP_URL: {{ b64enc .Values.ethereum_http_url | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gas-oracle
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  private-key: {{ b64enc .Values.gasOraclePrivateKey | quote }}
---
{{- if eq .Values.use_message_relayer true }}
apiVersion: v1
kind: Secret
metadata:
  name: message-relayer-key
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  MNEMONIC: {{ b64enc .Values.message_relayer.mnemonic | quote }}
{{ end }}
{{ end }}
