apiVersion: v1
kind: Service
metadata:
  name: sequencer
  labels:
    app: sequencer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: sequencer
  type: ClusterIP
  ports:
    - name: rpc
      port: 8545
    - name: websocket
      port: 8546
---
apiVersion: v1
kind: Service
metadata:
  name: data-transport-layer
  labels:
    app: data-transport-layer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: data-transport-layer
  type: ClusterIP
  ports:
    - name: http
      port: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: batch-submitter
  labels:
    app: batch-submitter
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: batch-submitter
  type: ClusterIP
  ports:
    - name: metrics
      port: 7300
---
{{- if eq .Values.use_hardhat true }}
apiVersion: v1
kind: Service
metadata:
  name: hardhat
  labels:
    app: hardhat
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: hardhat
  type: ClusterIP
  ports:
    - port: 9545
{{ end }}
---
{{- if eq .Values.use_deployer true }}
apiVersion: v1
kind: Service
metadata:
  name: deployer
  labels:
    app: deployer
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: deployer
  type: ClusterIP
  ports:
    - port: 8081
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: failover-proxy
  labels:
    app: failover-proxy
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: failover-proxy
  type: ClusterIP
  ports:
    - port: 8000
