{{- if eq (default false $.Values.monitoring_enabled) true }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: batch-submitter
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app: batch-submitter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: data-transport-layer
  name: data-transport-layer
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: data-transport-layer
{{- end }}